AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MP3 Tagger-Analyzer Lambda Deployment

Globals:
  Function:
    Timeout: 300  # 5 minutes
    MemorySize: 4096  # 4GB
    EphemeralStorage:
      Size: 2048  # 2GB temp storage

Resources:
  # S3 Bucket for file uploads
  Mp3StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub mp3-tagger-storage-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30  # Auto-delete files after 30 days

  # Lambda Function
  Mp3TaggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mp3-tagger-backend:latest
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3_BUCKET: !Ref Mp3StorageBucket
          PYTHONUNBUFFERED: '1'
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Mp3StorageBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # CloudFront Distribution for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub mp3-tagger-frontend-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  
  FrontendUrl:
    Description: CloudFront URL for frontend
    Value: !GetAtt CloudFrontDistribution.DomainName
  
  S3Bucket:
    Description: S3 bucket for file storage
    Value: !Ref Mp3StorageBucket
